import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ExternalLink, Info, Scale, Shield } from "lucide-react";

import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Textarea } from "@/components/ui/textarea";
import { invoke } from "@/lib/tauri-api";
import type { GuardrailsSettings } from "@/lib/types";

const HELVETY_URL = "https://helvety.com";

/** Maguna / Helvety terms (UI copy): informational; not individualized legal advice. */
function DisclaimerSections() {
  return (
    <div className="space-y-4 text-sm text-muted-foreground">
      <p className="text-foreground font-medium">
        By installing or using Maguna, you acknowledge and agree that:
      </p>
      <ul className="list-inside list-decimal space-y-3 marker:text-muted-foreground">
        <li>
          <strong className="text-foreground">No warranty.</strong> Maguna is provided
          &quot;as is&quot; and &quot;as available&quot;, without warranties of any
          kind, whether express or implied (including merchantability, fitness for a
          particular purpose, or non-infringement), to the maximum extent permitted by
          applicable law.
        </li>
        <li>
          <strong className="text-foreground">Not professional advice.</strong> Outputs
          are generated by probabilistic AI models running on your device. Nothing in
          the app constitutes medical, legal, financial, safety, or other professional
          advice. You are solely responsible for how you interpret and use outputs and
          for complying with laws that apply to you.
        </li>
        <li>
          <strong className="text-foreground">Harm and misuse.</strong> You must not use
          Maguna to develop or facilitate illegal activity, credible threats or
          harassment, exploitation of minors, or content intended to substantially harm
          people or animals. Guardrails are prompt-level guidance only; they do not
          reliably block all unsafe or illegal content. The acceptable-use summary below
          states Helvety&apos;s expectations in plain language; it does not replace
          applicable law.
        </li>
        <li>
          <strong className="text-foreground">Third-party weights.</strong> Models you
          download or import (for example GGUF files) remain subject to their respective
          licenses and are not owned by Helvety. Helvety does not endorse any particular
          output from a third-party model.
        </li>
        <li>
          <strong className="text-foreground">Limitation of liability.</strong> To the
          maximum extent permitted by applicable law, Helvety and its affiliates,
          directors, officers, employees, and contributors shall not be liable for any
          indirect, incidental, special, consequential, punitive, or exemplary damages,
          or for any loss of profits, data, goodwill, or other intangible losses,
          arising out of or in connection with your use of or inability to use Maguna,
          whether or not foreseeable and whether based on warranty, contract, tort
          (including negligence), or any other legal theory. The aggregate liability of
          Helvety for any claim arising from Maguna shall not exceed the fees you paid
          to Helvety specifically for Maguna in the twelve (12) months before the claim
          (if Maguna has been free in that period for you, that amount is treated as
          zero to the fullest extent mandatory law allows). Mandatory consumer
          protections in your jurisdiction are not overridden where the law forbids caps
          or disclaimers such as those above.
        </li>
        <li>
          <strong className="text-foreground">Indemnity.</strong> You agree to defend
          and indemnify Helvety and its affiliates against any claims, liabilities,
          damages, losses, and expenses (including reasonable attorneys&apos; fees)
          arising from your use of Maguna or your violation of applicable law or of
          these notices, except to the extent caused by Helvety&apos;s willful
          misconduct.
        </li>
      </ul>
      <Separator />
      <p className="text-foreground font-medium">Acceptable use (summary)</p>
      <p>
        Maguna runs local models—you are responsible for lawful, ethical use of the app,
        prompts, outputs, and any models you install. Below is an illustrative summary
        of uses we disallow or treat as misuse. It is not exhaustive; barred conduct
        includes anything unlawful or intended to hurt people, systems, or institutions
        in comparable ways.
      </p>
      <ul className="list-inside list-disc space-y-2 marker:text-muted-foreground">
        <li>
          <strong className="text-foreground">Serious illegality.</strong> No activity
          that violates criminal or civil laws that apply to you (including theft,
          fraud, invasion of privacy where prohibited, and violence).
        </li>
        <li>
          <strong className="text-foreground">Child safety.</strong> No sexual depiction
          or exploitation of minors, and no solicitation or facilitation of harm to
          children.
        </li>
        <li>
          <strong className="text-foreground">Harassment and threats.</strong> No
          credible threats, stalking, doxxing, or coordinated bullying intended to cause
          fear or serious emotional harm.
        </li>
        <li>
          <strong className="text-foreground">High-risk deception.</strong> No
          impersonation of professionals, enterprises, or public figures to scam,
          manipulate markets, interfere with democratic processes, or otherwise deceive
          others in high-risk contexts—unless you clearly label outputs as AI and have
          lawful authority or consent where required.
        </li>
        <li>
          <strong className="text-foreground">Security abuse.</strong> No malware,
          ransomware, phishing at scale, or attempts to compromise systems or accounts
          you do not own or lack permission to test.
        </li>
        <li>
          <strong className="text-foreground">Weapons and tactical harm.</strong> No use
          to design, obtain, or deploy weapons, explosives, biological or chemical harm,
          or illegal surveillance when the purpose is to injure people or violate law.
        </li>
      </ul>
      <Separator />
      <p className="text-xs italic">
        This notice is informational. Applicable consumer rights in your jurisdiction
        are not waived where they cannot legally be waived. If mandatory law provides
        you with protections that conflict with portions of the foregoing, those
        protections prevail.
      </p>
    </div>
  );
}

/** Practical habits for on-device assistants; wording is Helvety's. */
function SafeUseGuidelines() {
  return (
    <ul className="list-inside list-disc space-y-2 text-sm text-muted-foreground marker:text-muted-foreground">
      <li>
        <span className="text-foreground">Verify important facts</span>, especially
        before acting on health, legal, workplace, safety, or financial matters.
      </li>
      <li>
        <span className="text-foreground">
          Do not treat the model as an authority figure
        </span>{" "}
        or as a substitute for qualified humans.
      </li>
      <li>
        <span className="text-foreground">Respect privacy and consent</span> when
        submitting third-party personal data into prompts.
      </li>
      <li>
        <span className="text-foreground">Expect mistakes and bias</span>; offline
        models vary in quality and safety tuning.
      </li>
      <li>
        <span className="text-foreground">Report product issues</span> via your usual
        Helvety contact channels rather than relying on model outputs alone.
      </li>
    </ul>
  );
}

function guardrailsStatusSentence(g: GuardrailsSettings): string {
  if (g.customText != null && g.customText.trim().length > 0) {
    return "Guardrails are on with your custom policy (prepended ahead of each mode prompt).";
  }
  return "Guardrails are on using the built-in policy below.";
}

export function SettingsPage() {
  const [guardrails, setGuardrails] = useState<GuardrailsSettings | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setError(null);
    try {
      const gr = await invoke<GuardrailsSettings>("get_guardrails_settings");
      setGuardrails(gr);
    } catch (e) {
      setError(String(e));
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <div className="mx-auto flex max-w-4xl flex-col gap-6">
      <header>
        <h2 className="text-2xl font-semibold tracking-tight">Settings</h2>
        <p className="mt-1 text-sm text-muted-foreground">
          About Maguna, guardrails, acceptable use expectations, and limitations of
          liability.
        </p>
      </header>

      {error ? (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      ) : null}

      <Card>
        <CardHeader>
          <CardTitle className="text-base">About</CardTitle>
          <CardDescription>
            Maguna is an on-device desktop assistant by{" "}
            <a
              href={HELVETY_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 font-medium text-primary underline-offset-4 hover:underline"
            >
              Helvety
              <ExternalLink className="size-3.5 shrink-0 opacity-70" aria-hidden />
            </a>
            .
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-3 text-sm text-muted-foreground">
          <p>
            Models run locally via llama.cpp (through the bundled `llama-cpp-4` engine);
            prompts and transcripts stay on your machine unless you copy or export them.
            Helvety builds tools for natural, multilingual writing—not a warranty that
            any AI output is correct or safe.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <Shield className="size-4 shrink-0" aria-hidden />
            Guardrails (reference)
          </CardTitle>
          <CardDescription>
            {guardrails
              ? guardrailsStatusSentence(guardrails)
              : "Loading guardrail status..."}{" "}
            To replace the built-in prepended policy with custom wording, use{" "}
            <Link
              to="/models"
              className="font-medium text-primary underline-offset-4 hover:underline"
            >
              Model library
            </Link>
            .
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          <div>
            <Label
              htmlFor="settings-guardrails-builtin"
              className="mb-2 block text-xs font-medium uppercase tracking-wide text-muted-foreground"
            >
              Built-in Maguna policy (shown to the model when guardrails use the default
              text)
            </Label>
            <Textarea
              id="settings-guardrails-builtin"
              readOnly
              aria-readonly="true"
              rows={10}
              className="resize-none font-mono text-xs"
              value={guardrails?.builtInPolicyText ?? ""}
              placeholder={
                guardrails
                  ? "No policy text loaded."
                  : "Loading built-in guardrail text..."
              }
            />
          </div>
          {guardrails?.customText != null && guardrails.customText.trim().length > 0 ? (
            <div>
              <Label
                htmlFor="settings-guardrails-custom-readonly"
                className="mb-2 block text-xs font-medium uppercase tracking-wide text-muted-foreground"
              >
                Your custom guardrail policy (currently active instead of built-in
                default)
              </Label>
              <Textarea
                id="settings-guardrails-custom-readonly"
                readOnly
                aria-readonly="true"
                rows={Math.min(
                  24,
                  Math.max(8, guardrails.customText.split("\n").length + 4),
                )}
                className="resize-none font-mono text-xs"
                value={guardrails.customText}
              />
            </div>
          ) : null}
          <Alert>
            <Info className="size-4 shrink-0" aria-hidden />
            <AlertDescription className="text-xs leading-relaxed">
              Local models often follow system instructions but are not obligated to
              refuse; this is not the same kind of enforcement cloud APIs may apply
              through separate classifiers.
            </AlertDescription>
          </Alert>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <Info className="size-4 shrink-0" aria-hidden />
            Safe use (guidelines)
          </CardTitle>
          <CardDescription>
            Practical habits when working with probabilistic outputs from local models.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <SafeUseGuidelines />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <Scale className="size-4 shrink-0" aria-hidden />
            Terms &amp; disclaimers (Maguna)
          </CardTitle>
          <CardDescription>
            Please read carefully. These terms govern your relationship with Helvety for
            this product.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <DisclaimerSections />
        </CardContent>
      </Card>
    </div>
  );
}
